### ISSUE TITLE
Количество emoji  

### ISSUE THREAD

**Issue by dizolkin** [Animatea/python-multibar#1]
Можно ли сменить количество emoji c 20 например на 10?

**Comment by InspiredImpact** [comment]
> Можно ли сменить количество emoji c 20 например на 10?

Да, сейчас библиотека была полностью переработана, добавлено множество различных функций, в скором времени документация будет доделана. Разработка идёт полным ходом, ожидайте релиз :3

**Comment by InspiredImpact** [comment]
Здравствуйте! В текущей версии библиотеки длину прогрессбара можно установить изменив параметр length класса ProgressBar! См. в документации - https://animatea.github.io/python-multibar/multibar.impl/?h=ProgressBar
